from pathlib import Path
import re

root=Path('/mnt/data/work39b')
html=root/'app/templates/my_edits_studio.html'
s=html.read_text()

# CSS: make font styling explicit via a CSS variable and add independent background styling.
s=s.replace(".myed-card{position:relative;width:min(76%,620px);aspect-ratio:1.52;display:flex;flex-direction:column;justify-content:center;padding:30px 34px;border:3px solid #14211e;box-shadow:12px 12px 0 #14211e;color:#14211e}",
".myed-card{position:relative;width:min(76%,620px);aspect-ratio:1.52;display:flex;flex-direction:column;justify-content:center;padding:30px 34px;border:3px solid #14211e;box-shadow:12px 12px 0 #14211e;color:#14211e;background-color:var(--myed-bg-color,#ffe36a);background-image:var(--myed-bg-image,none);background-size:cover;background-position:center;background-repeat:no-repeat}.myed-card h2{font-family:var(--myed-font-family,Arial,sans-serif);font-weight:var(--myed-font-weight,800)}")
# Add look classes near existing style definitions
s=s.replace(".myed-card.elegant h2{font-family:Georgia,serif;font-style:italic;font-weight:500}.myed-card.sunny",
".myed-card.elegant h2{font-family:Georgia,serif;font-style:italic;font-weight:500}.myed-card.marker{border-style:dashed;box-shadow:7px 9px 0 #14211e}.myed-card.minimal{box-shadow:4px 4px 0 rgba(20,33,30,.12);border-width:2px}.myed-card.night{border-color:#dce9e7;box-shadow:9px 9px 0 #122027}.myed-card.playful{transform:rotate(-.6deg);box-shadow:8px 10px 0 rgba(20,33,30,.28)}.myed-card.sunny")
# Inputs: background selector lives inside existing Style More pop; no new outer section.
old="<div class=\"myed-pop\"><div class=\"myed-style-label\">Fonts</div><div class=\"myed-picks\">{% for v,n in [('serif','Classic'),('display','Display'),('light','Light'),('wide','Wide'),('typewriter','Typewriter'),('comic','Playful'),('caps','Caps'),('elegant','Elegant')] %}<label><input type=\"radio\" name=\"font_style\" value=\"{{v}}\"><span class=\"chip\">{{n}}</span></label>{% endfor %}</div><div class=\"myed-style-label\">Looks</div><div class=\"myed-picks\">{% for v,n in [('sunny','Sunny'),('pastel','Pastel'),('marker','Marker'),('minimal','Minimal'),('night','Night'),('playful','Playful')] %}<label><input type=\"radio\" name=\"design_style\" value=\"{{v}}\"><span class=\"chip\">{{n}}</span></label>{% endfor %}</div></div>"
new="<div class=\"myed-pop\"><div class=\"myed-style-label\">Fonts</div><div class=\"myed-picks\">{% for v,n in [('serif','Classic'),('display','Display'),('light','Light'),('wide','Wide'),('typewriter','Typewriter'),('comic','Playful'),('caps','Caps'),('elegant','Elegant')] %}<label><input type=\"radio\" name=\"font_style\" value=\"{{v}}\"><span class=\"chip\">{{n}}</span></label>{% endfor %}</div><div class=\"myed-style-label\">Looks</div><div class=\"myed-picks\">{% for v,n in [('sunny','Sunny'),('pastel','Pastel'),('marker','Marker'),('minimal','Minimal'),('night','Night'),('playful','Playful')] %}<label><input type=\"radio\" name=\"design_style\" value=\"{{v}}\"><span class=\"chip\">{{n}}</span></label>{% endfor %}</div><div class=\"myed-style-label\">Background</div><div class=\"myed-picks\">{% for v,n in [('solid','Solid'),('gradient','Gradient'),('sunset','Sunset'),('ocean','Ocean'),('paper','Paper'),('grid','Grid'),('dots','Dots'),('aurora','Aurora'),('dark','Dark'),('cream','Cream'),('lavender','Lavender'),('mintwash','Mint wash')] %}<label><input type=\"radio\" name=\"background_style\" value=\"{{v}}\"><span class=\"chip\">{{n}}</span></label>{% endfor %}</div></div>"
if old not in s:
    raise SystemExit('Style pop block not found')
s=s.replace(old,new)

# Add hidden field for background style.
s=s.replace('<input type="hidden" name="design_style" id="myedDesign" value="sunny">', '<input type="hidden" name="design_style" id="myedDesign" value="sunny"><input type="hidden" name="background_style" id="myedBackground" value="solid">')

# Load cards: pass persisted background when available. Jinja Row supports .keys().
s=s.replace("{{c.design_style|tojson}},{{c.signature_enabled|int}}", "{{c.design_style|tojson}},{{(c.background_style if 'background_style' in c.keys() else 'solid')|tojson}},{{c.signature_enabled|int}}")

# CSS helpers for option chips and background preview swatches are not necessary; use chips.
# JS variable + background catalog.
s=s.replace("const hidTitle=document.getElementById('myedTitle'), hidId=document.getElementById('myedCardId'), hidColor=document.getElementById('myedColor'), hidFont=document.getElementById('myedFont'), hidShape=document.getElementById('myedShape'), hidDesign=document.getElementById('myedDesign'), hidSig=document.getElementById('myedSig'), hidDec=document.getElementById('myedDecoration'), after=document.getElementById('myedAfter');",
"const hidTitle=document.getElementById('myedTitle'), hidId=document.getElementById('myedCardId'), hidColor=document.getElementById('myedColor'), hidFont=document.getElementById('myedFont'), hidShape=document.getElementById('myedShape'), hidDesign=document.getElementById('myedDesign'), hidBackground=document.getElementById('myedBackground'), hidSig=document.getElementById('myedSig'), hidDec=document.getElementById('myedDecoration'), after=document.getElementById('myedAfter');")
s=s.replace("const decoMap={", "const bgMap={solid:['none'],gradient:['linear-gradient(135deg,rgba(255,255,255,.10),rgba(255,255,255,.48))'],sunset:['linear-gradient(135deg,#ffd38a 0%,#ff9bb8 55%,#b39cff 100%)'],ocean:['linear-gradient(135deg,#9fe6ff 0%,#75c9dc 55%,#6e97d8 100%)'],paper:['repeating-linear-gradient(0deg,rgba(20,33,30,.055) 0 1px,transparent 1px 13px)'],grid:['linear-gradient(rgba(20,33,30,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(20,33,30,.08) 1px,transparent 1px)'],dots:['radial-gradient(rgba(20,33,30,.13) 1.1px,transparent 1.1px)'],aurora:['radial-gradient(circle at 20% 20%,rgba(119,236,216,.55),transparent 34%),radial-gradient(circle at 80% 80%,rgba(160,132,255,.50),transparent 38%)'],dark:['linear-gradient(135deg,#1d2930,#10181d)'],cream:['linear-gradient(135deg,#fff9df,#f5edce)'],lavender:['linear-gradient(135deg,#f0e9ff,#ddd0ff)'],mintwash:['linear-gradient(135deg,#eafff6,#c9f2e3)']};const fontMap={bold:['Arial,sans-serif','800'],soft:['Arial,sans-serif','500'],hand:['Georgia,serif','600'],mono:['ui-monospace,SFMono-Regular,Menlo,monospace','800'],serif:['Georgia,serif','700'],display:['Arial Black,Impact,sans-serif','900'],light:['Arial,sans-serif','400'],wide:['Arial Narrow,Arial,sans-serif','800'],typewriter:['Courier New,monospace','700'],comic:['Comic Sans MS,Trebuchet MS,cursive','800'],caps:['Arial,sans-serif','900'],elegant:['Georgia,serif','500']};\n  const decoMap={")
# Verify exact paint function replacement.
oldpaint="""  function paint(){\n    const c=get('color')||'yellow', f=get('font_style')||'bold', sh=get('shape_style')||'sticky', look=get('design_style')||'sunny', d=get('decoration')||'spark', sig=get('signature_enabled')!=='0';\n    let title=writeMode==='topic'?(body.value.trim()||hidTitle.value.trim()):hidTitle.value.trim();\n    let text=writeMode==='body'?body.value.trim():bodyText;\n    if(writeMode==='topic')topicText=body.value.trim(); else bodyText=body.value.trim();\n    card.className='myed-card '+c+' '+f+' '+sh+' '+look+' '+(title&&!text?'title-only':'')+' '+(!title&&text?'body-only':'');\n    tout.textContent=title||''; bout.textContent=text||'';\n    deco.textContent=decoMap[d]||'✦'; deco.classList.toggle('verified-badge',blueDecos.has(d)); brand.style.display=sig?'block':'none';\n    hidColor.value=c; hidFont.value=f; hidShape.value=sh; hidDesign.value=look; hidSig.value=sig?'1':'0'; hidDec.value=d;\n    syncSaveButtons();\n  }"""
newpaint="""  function paint(){\n    const c=get('color')||'yellow', f=get('font_style')||'bold', sh=get('shape_style')||'sticky', look=get('design_style')||'sunny', bg=get('background_style')||'solid', d=get('decoration')||'spark', sig=get('signature_enabled')!=='0';\n    let title=writeMode==='topic'?(body.value.trim()||hidTitle.value.trim()):hidTitle.value.trim();\n    let text=writeMode==='body'?body.value.trim():bodyText;\n    if(writeMode==='topic')topicText=body.value.trim(); else bodyText=body.value.trim();\n    card.className='myed-card '+c+' '+sh+' '+look+' '+(title&&!text?'title-only':'')+' '+(!title&&text?'body-only':'');\n    const font=fontMap[f]||fontMap.bold, bgImage=(bgMap[bg]&&bgMap[bg][0])||'none';\n    const palette=getComputedStyle(card), swatch=document.querySelector('input[name=color]:checked + .sw');\n    const baseColor=swatch ? getComputedStyle(swatch).backgroundColor : '';\n    card.style.setProperty('--myed-font-family',font[0]); card.style.setProperty('--myed-font-weight',font[1]);\n    if(baseColor) card.style.setProperty('--myed-bg-color',baseColor);\n    card.style.setProperty('--myed-bg-image',bgImage);\n    if(bg==='dark') card.style.color='#fff'; else card.style.color='';\n    tout.textContent=title||''; bout.textContent=text||'';\n    deco.textContent=decoMap[d]||'✦'; deco.classList.toggle('verified-badge',blueDecos.has(d)); brand.style.display=sig?'block':'none';\n    hidColor.value=c; hidFont.value=f; hidShape.value=sh; hidDesign.value=look; hidBackground.value=bg; hidSig.value=sig?'1':'0'; hidDec.value=d;\n    syncSaveButtons();\n  }"""
if oldpaint not in s:
    raise SystemExit('paint block not found')
s=s.replace(oldpaint,newpaint)

# loadMyEdits signature + selector + existing cards default.
s=s.replace("window.loadMyEdits=(id,title,b,c,f,sh,d,sig,dec)=>{", "window.loadMyEdits=(id,title,b,c,f,sh,d,bg,sig,dec)=>{")
s=s.replace("document.querySelectorAll('input[name=design_style]').forEach(x=>x.checked=x.value===d);", "document.querySelectorAll('input[name=design_style]').forEach(x=>x.checked=x.value===d);document.querySelectorAll('input[name=background_style]').forEach(x=>x.checked=x.value===(bg||'solid'));")

# robust change handler: explicitly accept any picker, including hidden-pop font/background, then repaint.
s=s.replace("const input=e.target.closest('.myed-pop input');\n    if(!input)return;\n    closeOpen();\n    paint();", "const input=e.target.closest('.myed-pop input');\n    if(!input)return;\n    closeOpen();\n    paint();")

# Current direct radio listeners include all .myed-picks input, enough, but keep event handling simple.
html.write_text(s)

# Backend schema/save/export.
routes=root/'app/routes.py'; r=routes.read_text()
r=r.replace("design_style=request.form.get('design_style','sunny').strip().lower()", "design_style=request.form.get('design_style','sunny').strip().lower(); background_style=request.form.get('background_style','solid').strip().lower()")
r=r.replace("if design_style not in {'sunny','pastel','marker','minimal','night','playful'}: design_style='sunny'", "if design_style not in {'sunny','pastel','marker','minimal','night','playful'}: design_style='sunny'\n    if background_style not in {'solid','gradient','sunset','ocean','paper','grid','dots','aurora','dark','cream','lavender','mintwash'}: background_style='solid'")
r=r.replace("SET folder_id=?,title=?,body=?,color=?,font_style=?,shape_style=?,design_style=?,qr_enabled=?,signature_enabled=?,decoration=?,updated_at=?", "SET folder_id=?,title=?,body=?,color=?,font_style=?,shape_style=?,design_style=?,background_style=?,qr_enabled=?,signature_enabled=?,decoration=?,updated_at=?")
r=r.replace("(folder_id,title,body,color,font_style,shape_style,design_style,qr_enabled,signature_enabled,decoration,now(),card_id,user['id'])", "(folder_id,title,body,color,font_style,shape_style,design_style,background_style,qr_enabled,signature_enabled,decoration,now(),card_id,user['id'])")
r=r.replace("INSERT INTO stuff_cards(user_id,folder_id,title,body,color,font_style,shape_style,design_style,qr_enabled,signature_enabled,decoration,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)", "INSERT INTO stuff_cards(user_id,folder_id,title,body,color,font_style,shape_style,design_style,background_style,qr_enabled,signature_enabled,decoration,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)")
r=r.replace("(user['id'],folder_id,title,body,color,font_style,shape_style,design_style,qr_enabled,signature_enabled,decoration,now(),now())", "(user['id'],folder_id,title,body,color,font_style,shape_style,design_style,background_style,qr_enabled,signature_enabled,decoration,now(),now())")
# export proxy
r=r.replace("self._export_design=r['design_style'] if 'design_style' in r.keys() else 'sunny'", "self._export_design=r['design_style'] if 'design_style' in r.keys() else 'sunny'\n            self._export_background=r['background_style'] if 'background_style' in r.keys() else 'solid'")
# export canvas reads bg
r=r.replace("design=getattr(card,'_export_design','sunny') or 'sunny'\n    decoration=", "design=getattr(card,'_export_design','sunny') or 'sunny'\n    background=getattr(card,'_export_background','solid') or 'solid'\n    decoration=")
# export independent background after img creation (before playful decorations)
r=r.replace("img=Image.new('RGB',(W,H),(245,245,239)); d=ImageDraw.Draw(img)\n    # soft playful background", "img=Image.new('RGB',(W,H),(245,245,239)); d=ImageDraw.Draw(img)\n    bg_overlays={\n        'gradient':((255,255,255),(210,245,235)),\n        'sunset':((255,210,150),(205,170,255)),\n        'ocean':((165,235,255),(105,150,220)),\n        'paper':((255,255,250),(235,240,230)),\n        'dark':((28,40,48),(15,24,30)),\n        'cream':((255,249,223),(245,237,206)),\n        'lavender':((241,233,255),(220,207,255)),\n        'mintwash':((234,255,247),(200,241,224))\n    }\n    if background in bg_overlays:\n        a,b=bg_overlays[background]\n        for yy in range(H):\n            t=yy/max(1,H-1); col=tuple(int(a[i]*(1-t)+b[i]*t) for i in range(3)); d.line((0,yy,W,yy),fill=col)\n    elif background=='grid':\n        d.rectangle((0,0,W,H),fill=(247,247,242))\n        for x in range(0,W,55): d.line((x,0,x,H),fill=(220,225,221),width=1)\n        for y2 in range(0,H,55): d.line((0,y2,W,y2),fill=(220,225,221),width=1)\n    elif background=='dots':\n        d.rectangle((0,0,W,H),fill=(247,249,245))\n        for yy in range(20,H,36):\n            for xx in range(20,W,36): d.ellipse((xx-2,yy-2,xx+2,yy+2),fill=(205,213,209))\n    elif background=='aurora':\n        d.rectangle((0,0,W,H),fill=(238,246,241))\n        d.ellipse((-240,-180,700,700),fill=(180,245,224))\n        d.ellipse((930,400,1800,1150),fill=(195,175,255))\n    # soft playful background")
# Prevent design from overwriting independently selected export background for dark only; keep design as style.
r=r.replace("if design=='night': bgc,inkc,acc=(23,35,43),(248,251,250),(121,225,211)", "if design=='night': inkc,acc=(248,251,250),(121,225,211)\n    if background=='dark': bgc,inkc=(37,49,58),(248,251,250)")
routes.write_text(r)

# DB migration registration
p=root/'app/db.py'; d=p.read_text()
needle="'decoration': \"ALTER TABLE stuff_cards ADD COLUMN decoration TEXT NOT NULL DEFAULT 'spark'\","
if needle not in d: raise SystemExit('db migration needle not found')
d=d.replace(needle, needle+"\n                'background_style': \"ALTER TABLE stuff_cards ADD COLUMN background_style TEXT NOT NULL DEFAULT 'solid'\",")
p.write_text(d)

# Also make the main cards page preserve the field when opening edits if route uses the same loader in the future.

print('patched')
